version: "3.3"
services:
    chrome:
        image: selenium/node-chrome:3.141.59-oxygen
        environment:
            HUB_HOST: 'selenium-hub'
            HUB_PORT: '4444'
        logging:
            driver: none
        links:
            - selenium-hub
        volumes:
            - source: '/dev/shm'
              target: '/dev/shm'
              type: 'bind'
    database:
        image: postgres:latest
        environment:
            POSTGRES_DB: 'prixfixe'
            POSTGRES_PASSWORD: 'hunter2'
            POSTGRES_USER: 'dbuser'
        logging:
            driver: none
        ports:
            - 2345:5432
    firefox:
        image: selenium/node-firefox:3.141.59-oxygen
        environment:
            HUB_HOST: 'selenium-hub'
            HUB_PORT: '4444'
        logging:
            driver: none
        links:
            - selenium-hub
        volumes:
            - source: '/dev/shm'
              target: '/dev/shm'
              type: 'bind'
    selenium-hub:
        image: selenium/hub:3.141.59-oxygen
        logging:
            driver: none
        ports:
            - 4444:4444
    test:
        environment:
            DOCKER: 'true'
            TARGET_ADDRESS: 'http://prixfixe-server:8888'
            DB_ADDRESS: 'postgres://dbuser:hunter2@database:5432/prixfixe?sslmode=disable'
        links:
            - selenium-hub
            - prixfixe-server
        build:
            context: '../../../'
            dockerfile: 'environments/testing/dockerfiles/frontend-tests.Dockerfile'
        depends_on:
            - firefox
            - chrome
    prixfixe-server:
        build:
            context: '../../../'
            dockerfile: 'environments/testing/dockerfiles/frontend-tests-server.Dockerfile'
        environment:
            CONFIGURATION_FILEPATH: '/etc/config.toml'
        ports:
            - 80:8888
        links:
            - database
