version: "3.8"
services:
    redis:
        hostname: worker_queue
        image: redis:6-buster
        container_name: redis
        ports:
            - '6379:6379'
        logging:
            driver: none
    postgres:
        container_name: postgres
        hostname: pgdatabase
        image: postgres:10
        environment:
            POSTGRES_DB: 'prixfixe'
            POSTGRES_PASSWORD: 'hunter2'
            POSTGRES_USER: 'dbuser'
        logging:
            driver: none
        ports:
            - '5432:5432'
    elasticsearch:
        image: elasticsearch:7.14.1
        ports:
            - '9200:9200'
            - '9300:9300'
        environment:
            discovery.type: 'single-node'
        healthcheck:
            test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
            interval: 30s
            timeout: 30s
            retries: 3
        logging:
            driver: none
    workers:
        container_name: integration_tests_workers
        build:
            context: '../../../'
            dockerfile: 'environments/testing/dockerfiles/workers.Dockerfile'
        environment:
            CONFIGURATION_FILEPATH: '/etc/service.config'
            PRIXFIXE_WORKERS_LOCAL_CONFIG_STORE_KEY: 'SUFNQVdBUkVUSEFUVEhJU1NFQ1JFVElTVU5TRUNVUkU='
        volumes:
            - source: '../../../environments/testing/config_files/integration-tests-config.json'
              target: '/etc/service.config'
              type: 'bind'
    prixfixe_api_server:
        hostname: api_server
        container_name: integration_tests_server
#        logging:
#            driver: none
        depends_on:
            - workers
        environment:
            USE_NOOP_LOGGER: 'nope'
            CONFIGURATION_FILEPATH: '/etc/service.config'
            PRIXFIXE_SERVER_LOCAL_CONFIG_STORE_KEY: 'SUFNQVdBUkVUSEFUVEhJU1NFQ1JFVElTVU5TRUNVUkU='
        ports:
            - '8000:8000'
        build:
            context: '../../../'
            dockerfile: 'environments/testing/dockerfiles/integration-server.Dockerfile'
        volumes:
            - source: '../../../environments/local/certificates/cert.pem'
              target: '/etc/certs/cert.pem'
              type: 'bind'
            - source: '../../../environments/local/certificates/key.pem'
              target: '/etc/certs/key.pem'
              type: 'bind'
            - source: '../../../environments/testing/config_files/integration-tests-config.json'
              target: '/etc/service.config'
              type: 'bind'
    test:
        environment:
            TARGET_ADDRESS: 'http://api_server:8000'
            TARGET_DATABASE: 'postgres://dbuser:hunter2@pgdatabase:5432/prixfixe?sslmode=disable'
        depends_on:
            - workers
        links:
            - prixfixe_api_server
        build:
            context: '../../../'
            dockerfile: 'environments/testing/dockerfiles/integration-tests.Dockerfile'
        container_name: 'integration_tests'
