receivers:
  otlp:
    protocols:
      grpc:

  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
      paging:
      process:
      processes:

exporters:
  otlp:
    endpoint: 0.0.0.0:4317

processors:
  probabilistic_sampler:
    hash_seed: 22
    sampling_percentage: ${SAMPLING_PERCENTAGE}

extensions:
  health_check:
  pprof:
  zpages:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [probabilistic_sampler]
      exporters: [otlp]
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [probabilistic_sampler]
      exporters: [otlp]