extensions:
  health_check:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  awsecscontainermetrics:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'prixfixe-api-server'
          scrape_interval: 5s
          scrape_timeout: 5s
          metrics_path: '/metrics'
          scheme: 'http'

processors:
  traces:
    timeout: 1s
    send_batch_size: 50
  metrics:
    timeout: 60s
  resourcedetection:
    detectors:
      - env
      - system
      - ecs
      - ec2

exporters:
  awsxray:
  awsemf/application:
    namespace: ECS/AWSOTel/Application
    log_group_name: '/aws/ecs/application/metrics'
    dimension_rollup_option: ZeroAndSingleDimensionRollup
    resource_to_telemetry_conversion:
      enabled: true
  awsprometheusremotewrite:
    endpoint: https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push
    headers:
      Authorization: "Basic Mjc2OTUyOmV5SnJJam9pTW1WbE1URmtZbUk0TW1FeU9EVXhNbU5rWW1JM1pEWm1ZamxpTWpnM09HSTVNakJqTnpsalppSXNJbTRpT2lKQlYxTWdSR1YySWl3aWFXUWlPalEyTURRek1YMD0="

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resourcedetection, traces]
      exporters: [awsxray]
    metrics:
      receivers: [otlp]
      processors: [resourcedetection, metrics]
      exporters: [awsprometheusremotewrite,awsemf/application]

  extensions: [health_check]