extensions:
  health_check:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  awsecscontainermetrics:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'prixfixe-api-server'
          scrape_interval: 5s
          scrape_timeout: 5s
          metrics_path: '/metrics'
          scheme: 'http'

processors:
  batch/metrics:
    timeout: 60s
  resourcedetection:
    detectors:
      - env
      - system
      - ecs
      - ec2

exporters:
  awsprometheusremotewrite:
    endpoint: https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push
    basic_auth:
      username: 276952
      password: eyJrIjoiMmVlMTFkYmI4MmEyODUxMmNkYmI3ZDZmYjliMjg3OGI5MjBjNzljZiIsIm4iOiJBV1MgRGV2IiwiaWQiOjQ2MDQzMX0=

service:
  pipelines:
    metrics/application:
      receivers: [otlp]
      processors: [resourcedetection, batch/metrics]
      exporters: [awsprometheusremotewrite]
    metrics:
      receivers: [awsecscontainermetrics]
      exporters: [awsprometheusremotewrite]

  extensions: [health_check]