receivers:
  otlp:
    protocols:
      grpc:

exporters:
  otlp:
    endpoint: 0.0.0.0:4317

processors:
  batch:

extensions:
  health_check:
  pprof:
  zpages:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
