---
version: '3.3'
services:
    database:
        image: postgres:latest
        environment:
            POSTGRES_DB: 'prixfixe'
            POSTGRES_PASSWORD: 'hunter2'
            POSTGRES_USER: 'dbuser'
        logging:
            driver: none
        ports:
            - 2345:5432
    load-tests:
        environment:
            TARGET_ADDRESS: 'http://prixfixe-server:8888'
        links:
            - prixfixe-server
        build:
            context: '../../../../'
            dockerfile: 'environments/testing/dockerfiles/load-tests.Dockerfile'
    prixfixe-server:
        links:
            - database
            - tracing-server
            - prometheus
            - loki
            - promtail
        volumes:
            - source: '../../../../environments/testing/config_files/integration-tests-postgres.toml'
              target: '/etc/config.toml'
              type: 'bind'
