version: "3.3"
services:
    database:
        image: postgres:latest
        environment:
            POSTGRES_DB: 'prixfixe'
            POSTGRES_PASSWORD: 'hunter2'
            POSTGRES_USER: 'dbuser'
        logging:
            driver: none
        ports:
            - 2345:5432
    prixfixe_server:
        environment:
            CONFIGURATION_FILEPATH: '/etc/config.toml'
        ports:
            - 80:8888
        links:
            - database
        build:
            context: '../../../../'
            dockerfile: 'environments/testing/dockerfiles/integration-server-postgres.Dockerfile'
    test:
        environment:
            TARGET_ADDRESS: 'http://prixfixe_server:8888'
        links:
            - prixfixe_server
        build:
            context: '../../../../'
            dockerfile: 'environments/testing/dockerfiles/integration-tests.Dockerfile'
        container_name: 'integration_tests'
