apiVersion: v1
kind: Namespace
metadata:
  name: dev-service

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev-service
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-account-binding
  namespace: dev-service
subjects:
- kind: User
  name: api-server@dinner-done-better-dev.iam.gserviceaccount.com

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server-deployment
  namespace: dev-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - name: api-server-container
          image: us-central1-docker.pkg.dev/dinner-done-better-dev/containers/api_server:latest
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: api-server-service
  namespace: dev-service
spec:
  selector:
    app: api-server
  ports:
    - protocol: TCP
      port: 80         # Port for external traffic
      targetPort: 8000 # Port your API server container listens on
  type: LoadBalancer   # Expose the service externally using GCP's load balancer
