apiVersion: v1
kind: Namespace
metadata:
  name: dev-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server-deployment
  namespace: dev-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - name: api-server-container
          image: us-central1-docker.pkg.dev/dinner-done-better-dev/containers/api_server:latest
          ports:
            - containerPort: 8000
          env:
            - name: RUNNING_IN_GOOGLE_CLOUD_RUN
              value: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: api-server-service
  namespace: dev-service
spec:
  selector:
    app: api-server
  ports:
    - protocol: TCP
      port: 80         # Port for external traffic
      targetPort: 8000 # Port your API server container listens on
  type: LoadBalancer   # Expose the service externally using GCP's load balancer
