version: "3.8"
services:
    workers:
        container_name: workers
        environment:
            PRIXFIXE_WORKERS_LOCAL_CONFIG_STORE_KEY: 'SUFNQVdBUkVUSEFUVEhJU1NFQ1JFVElTVU5TRUNVUkU='
            CONFIGURATION_FILEPATH: '/etc/service.config'
            JAEGER_DISABLED: 'false'
        volumes:
            - source: '../..'
              target: '/go/src/github.com/prixfixeco/api_server'
              type: 'bind'
            - source: '../../environments/local/service.config'
              target: '/etc/service.config'
              type: 'bind'
        build:
            context: '../../'
            dockerfile: 'environments/local/workers.Dockerfile'
    prixfixe-server:
        container_name: api_server
        depends_on:
          - workers
        environment:
            PRIXFIXE_SERVER_LOCAL_CONFIG_STORE_KEY: 'SUFNQVdBUkVUSEFUVEhJU1NFQ1JFVElTVU5TRUNVUkU='
            CONFIGURATION_FILEPATH: '/etc/service.config'
            JAEGER_DISABLED: 'false'
        ports:
            - '8888:8888'
        volumes:
            - source: '../../environments/local/certificates/cert.pem'
              target: '/etc/certs/cert.pem'
              type: 'bind'
            - source: '../../environments/local/certificates/key.pem'
              target: '/etc/certs/key.pem'
              type: 'bind'
            - source: '../../environments/local/service.config'
              target: '/etc/service.config'
              type: 'bind'
            - source: '../../'
              target: '/go/src/github.com/prixfixeco/api_server'
              type: 'bind'
        build:
            context: '../../'
            dockerfile: 'environments/local/Dockerfile'