version: "3.3"
services:
    database:
        image: postgres:latest
        environment:
            POSTGRES_DB: "prixfixe"
            POSTGRES_PASSWORD: "hunter2"
            POSTGRES_USER: "dbuser"
        logging:
            driver: none
        ports:
            - 2345:5432
    prixfixe-server:
        environment:
            CONFIGURATION_FILEPATH: "/etc/config.toml"
            DOCKER: "true"
        ports:
            - 80:8888
        links:
            - database
        build:
            context: "../../"
            dockerfile: "environments/testing/dockerfiles/integration-server.Dockerfile"
    test:
        environment:
            DOCKER: "true"
            TARGET_ADDRESS: "http://prixfixe-server:8888"
            DB_ADDRESS: "postgres://dbuser:hunter2@database:5432/prixfixe?sslmode=disable"
        links:
            - prixfixe-server
        build:
            context: "../.."
            dockerfile: "environments/testing/dockerfiles/integration-tests.Dockerfile"
        container_name: "postgres_integration_tests"
