on: # [pull_request]
  pull_request:
    paths:
      - pkg/**
      - cmd/**
      - internal/**
name: Build Cloud Functions
jobs:
  setup:
    strategy:
      matrix:
        go-version: [ '1.19.x' ]
        function: [
          'data_changes',
          'meal_plan_finalizer',
          'meal_plan_task_creator',
          'meal_plan_grocery_list_initializer',
        ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      # get rid of the mod and sum file for this function just to ensure it builds
      - name: Build ${{ matrix.function }} function
        run: rm -rf cmd/functions/${{ matrix.function }}/go.{mod,sum}

      - name: Build ${{ matrix.function }} function
        run: go build github.com/prixfixeco/backend/cmd/functions/${{ matrix.function }}
