on:
  pull_request:
    paths:
      - pkg
      - cmd
      - internal
name: Dependency Injection
jobs:
 check:
   strategy:
     matrix:
       go-version: [ '1.18.x' ]
   runs-on: ubuntu-latest
   steps:
     - name: Install Go
       uses: actions/setup-go@v2
       with:
         go-version: ${{ matrix.go-version }}

     - name: Checkout code
       uses: actions/checkout@v2

     - name: Install wire
       run: go install github.com/google/wire/cmd/wire@latest

     - name: Test dependency injection
       run: wire gen github.com/prixfixeco/api_server/internal/build/server
