on: # [pull_request]
  pull_request:
    paths:
      - pkg/**
      - cmd/**
      - internal/**
name: check
jobs:
 dependency_injection:
   strategy:
     matrix:
       go-version: [ '1.20.x' ]
   runs-on: ubuntu-latest
   steps:
     - name: Install Go
       uses: actions/setup-go@v4
       with:
         go-version: ${{ matrix.go-version }}

     - name: Checkout code
       uses: actions/checkout@v3

     - name: Install wire
       run: go install github.com/google/wire/cmd/wire@latest

     - name: Test dependency injection
       run: wire gen github.com/prixfixeco/backend/internal/build/server
