on: # [pull_request]
  push:
    branches:
      - dev
name: deploy
jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19.x'

      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.DEV_GOOGLE_CLOUD_CREDENTIALS }}'

      # Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.4
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_API_TOKEN  }}

      - name: Terraform Init
        working-directory: environments/dev/terraform
        id: init
        run: terraform init

      - name: Build API server container
        run: |
          docker build --tag gcr.io/prixfixe-dev/api_server:${{  github.sha }} --file environments/dev/dockerfiles/api_server.Dockerfile .
          docker build --tag gcr.io/prixfixe-dev/api_server:latest --file environments/dev/dockerfiles/api_server.Dockerfile .

      - name: Build data changes cloud function directory
        run: ./scripts/build_cloud_function.sh data_changes

      - name: Build meal plan finalizer cloud function directory
        run: ./scripts/build_cloud_function.sh meal_plan_finalizer

      - name: Build meal plan task creator cloud function directory
        run: ./scripts/build_cloud_function.sh meal_plan_task_creator

      - name: Build meal plan grocery list initializer cloud function directory
        run: ./scripts/build_cloud_function.sh meal_plan_grocery_list_initializer

      - name: copy API server config file
        working-directory: environments/dev
        run: |
          cp config_files/service-config.json terraform/service-config.json

      - name: Terraform Validate
        working-directory: environments/dev/terraform
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: environments/dev/terraform

      - name: Push API server container
        run: |
          docker push gcr.io/prixfixe-dev/api_server:${{  github.sha }}
          docker push gcr.io/prixfixe-dev/api_server:latest

      # if this step fails, you need to add the `Service Account User` role to the GitHub Actions IAM Principal.
      - id: deploy-api-server
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: 'api-server'
          project_id: 'prixfixe-dev'
          image: 'gcr.io/prixfixe-dev/api_server'
