on: [pull_request]
name: Deploy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.3'

      - name: Build writes worker lambda
        run: go build -o writes_worker github.com/prixfixeco/api_server/cmd/workers/lambdas/writes

      - name: Zip writer lambda
        run: zip writer_worker.zip writes_worker

      - name: Upload writer lambda
        uses: actions/upload-artifact@v2
        with:
          name: writer_lambda
          path: writer_worker.zip
          retention-days: 1

      - name: Build updates worker lambda
        run: go build -o updates_worker github.com/prixfixeco/api_server/cmd/workers/lambdas/updates

      - name: Zip updater lambda
        run: zip updater_worker.zip updates_worker

      - name: Upload updater lambda
        uses: actions/upload-artifact@v2
        with:
          name: updater_lambda
          path: updater_worker.zip
          retention-days: 1

      - name: Build archives worker lambda
        run: go build -o archiver_worker github.com/prixfixeco/api_server/cmd/workers/lambdas/archives

      - name: Zip archiver lambda
        run: zip archiver_worker.zip archiver_worker

      - name: Upload archiver lambda
        uses: actions/upload-artifact@v2
        with:
          name: archiver_lambda
          path: archiver_worker.zip
          retention-days: 1

      - name: Build data changes worker lambda
        run: go build -o data_changes_worker github.com/prixfixeco/api_server/cmd/workers/lambdas/data_changes

      - name: Zip data changes lambda
        run: zip data_changes_worker.zip data_changes_worker

      - name: Upload data changes lambda
        uses: actions/upload-artifact@v2
        with:
          name: data_changes_lambda
          path: data_changes_worker.zip
          retention-days: 1

      - name: Build chores worker lambda
        run: go build -o chores_worker github.com/prixfixeco/api_server/cmd/workers/lambdas/chores

      - name: Zip chores lambda
        run: zip chores_worker.zip chores_worker

      - name: Upload chores lambda
        uses: actions/upload-artifact@v2
        with:
          name: chores_lambda
          path: chores_worker.zip
          retention-days: 1

  scaffold:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_API_TOKEN  }}

      - name: Terraform Init
        working-directory: environments/dev/terraform
        id: init
        run: terraform init

      - name: Terraform Format
        working-directory: environments/dev/terraform
        id: fmt
        run: terraform fmt -check

      - name: copy config file
        working-directory: environments/dev
        run: cp config_files/service-config.json terraform/service-config.json

      - name: Terraform Validate
        working-directory: environments/dev/terraform
        id: validate
        run: terraform validate -no-color

      # - name: Terraform Plan
      #   working-directory: environments/dev/terraform
      #   id: plan
      #   if: github.event_name == 'pull_request'
      #   run: terraform plan -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve
        # if: github.event_name == 'release'
        working-directory: environments/dev/terraform

  deploy:
    needs: [
      scaffold,
      build,
    ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build --tag $ECR_REGISTRY/api_server:$IMAGE_TAG --file environments/dev/dockerfiles/api_server.Dockerfile .
          docker push $ECR_REGISTRY/api_server:$IMAGE_TAG
          docker build --tag $ECR_REGISTRY/api_server:latest --file environments/dev/dockerfiles/api_server.Dockerfile .
          docker push $ECR_REGISTRY/api_server:latest

      - name: Download writer lambda
        uses: actions/download-artifact@v2
        with:
          name: writer_lambda
          path: artifacts

      - name: Deploy writer lambda
        working-directory: artifacts
        run: aws lambda update-function-code --function-name writes_worker --zip-file fileb://writer_worker.zip

      - name: Download updater lambda
        uses: actions/download-artifact@v2
        with:
          name: updater_lambda
          path: artifacts

      - name: Deploy updater lambda
        working-directory: artifacts
        run: aws lambda update-function-code --function-name updates_worker --zip-file fileb://updater_worker.zip

      - name: Download archiver lambda
        uses: actions/download-artifact@v2
        with:
          name: archiver_lambda
          path: artifacts

      - name: Deploy archiver lambda
        working-directory: artifacts
        run: aws lambda update-function-code --function-name archiver_worker --zip-file fileb://archiver_worker.zip

      - name: Download data changes lambda
        uses: actions/download-artifact@v2
        with:
          name: data_changes_lambda
          path: artifacts

      - name: Deploy data changes lambda
        working-directory: artifacts
        run: aws lambda update-function-code --function-name data_changes_worker --zip-file fileb://data_changes_worker.zip

      - name: Download chores lambda
        uses: actions/download-artifact@v2
        with:
          name: chores_lambda
          path: artifacts

      - name: Deploy data changes lambda
        working-directory: artifacts
        run: aws lambda update-function-code --function-name chores_worker --zip-file fileb://chores_worker.zip
