on: [gollum]
#  pull_request:
#    paths:
#      - pkg/**
#      - internal/**
name: generate
jobs:
 configs:
   strategy:
     matrix:
       go-version: [ '1.20.x' ]
   runs-on: ubuntu-latest
   steps:
     - name: Install Go
       uses: actions/setup-go@v4
       with:
         go-version: ${{ matrix.go-version }}

     - name: Checkout code
       uses: actions/checkout@v3

     - name: Test build
       run: make configs