on:
  push:
    branches:
      - dev
name: Integration Tests
jobs:
  integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run the integration tests
        run: make integration_tests
