on: # [gollum]
  pull_request:
    paths:
      - pkg/**
      - cmd/**
      - internal/**
      - tests/**
name: Lint
jobs:
  golang:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: make lint
