on:
  pull_request:
    paths:
      - pkg/**
      - cmd/**
      - internal/**
name: Tests
jobs:
 unit:
   strategy:
     matrix:
       go-version: [ '1.18.x' ]
   runs-on: ubuntu-latest
   steps:
     - name: Install Go
       uses: actions/setup-go@v2
       with:
         go-version: ${{ matrix.go-version }}

     - name: Checkout code
       uses: actions/checkout@v2

     - name: Test build
       run: go build `go list ./... | grep -Ev '(cmd|tests|testutil|mock|fake)'`

     - name: Unit tests
       run: go test -cover -shuffle=on -race -failfast `go list ./... | grep -Ev '(cmd|tests|testutil|mock|fake)'`
