on: [pull_request]
#  pull_request:
#    paths:
#      - pkg/**
#      - internal/**
name: tests
jobs:
 unit:
   strategy:
     matrix:
       go-version: [ '1.20.x' ]
   runs-on: ubuntu-latest
   steps:
     - name: Install Go
       uses: actions/setup-go@v4
       with:
         go-version: ${{ matrix.go-version }}

     - name: Checkout code
       uses: actions/checkout@v3

     - name: Test build
       run: go build `go list ./... | grep -Ev '(cmd|tests|testutil|mock|fake)'`

     - name: Unit tests
       run: go test -cover -shuffle=on -race -failfast `go list ./... | grep -Ev '(cmd|tests|testutil|mock|fake)'`
