version: "3.3"
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - source: /home/sysadmin/.docker/config.json
        target: /config.json
        type: bind
      - source: /var/run/docker.sock
        target: /var/run/docker.sock
        type: bind
  caddy:
    container_name: caddy
    image: caddy:2
    ports:
      - "443:443"
    links:
      - prixfixe_server
    volumes:
      - source: /home/sysadmin/Caddyfile
        target: /etc/caddy/Caddyfile
        type: bind
      - source: /home/sysadmin/caddy_data
        target: /data
        type: bind
  prixfixe-server:
    container_name: prixfixe
    image: registry.gitlab.com/prixfixe/prixfixe:dev
    environment:
      PRIXFIXE_SERVICE_LOCAL_SECRET_STORE_KEY: 'SUFNQVdBUkVUSEFUVEhJU1NFQ1JFVElTVU5TRUNVUkU='
      CONFIGURATION_FILEPATH: '/etc/prixfixe.config'
      JAEGER_DISABLED: 'false'
    ports:
      - "8888:8888"
    volumes:
      - source: /home/sysadmin/prixfixe.config
        target: /etc/prixfixe.config
        type: bind
      - source: /home/sysadmin/prixfixe_search_indices
        target: /etc/prixfixe_search_indices
        type: bind
